version: '3'

services:
  myWebServer:
    image: nginx:alpine
    container_name: myNginx
    build:
      context: /
      args:
        HostDir: /root/myFiles

    volumes:
      - /root/myFiles:/usr/share/nginx/html

    ports:
      - 8080:80
    networks:
      - myNetwork

    environment:
      - HOST=mysite.com
      - PORT=8080
      - HostDir=/root/myFiles
      - ContainerDir=/usr/share/nginx/html
    tty: true

  db:
    image: mysql:latest
    container_name: mySQL
    command: --innodb_use_native_aio=0
    volumes:
      - myVolume:/var/lib/mysql
    networks:
      - myNetwork
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    tty: true

volumes:
  myVolume:

networks:
  myNetwork:
